### ISSUE TITLE
Show diff comments in context

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#63] opened 2022-09-20 13:35 UTC
I'm coming back to [a review that's been paused for a month](https://codeapprove.com/pr/tiny-pilot/tinypilot/1079), and I'm realizing I can't find a way to make CodeApprove show comment threads in context.

For example, for a comment like this:

![image](https://user-images.githubusercontent.com/7783288/191267950-203f5893-92ae-4671-ba3e-730f9e178eea.png)

I'd like to be able to see it on the left side of the diff like this:

![image](https://user-images.githubusercontent.com/7783288/191268622-f347c9f9-5618-490d-ac03-2ddb340ca7a6.png)

# Similar implementations

## Gerrit

![image](https://user-images.githubusercontent.com/7783288/191269218-346aa92c-7db4-4761-b07e-68bb037f242f.png)

## Reviewable

They also have a good implementation but they seem to be [having an outage right now](https://bit.ly/3SjXMtO).

**Comment by samatcodeapprove** [comment] 2022-09-21 07:12
Ah this is a good one! So basically for a comment that is "outdated" where there is no right-side line to attach it to, I should show the comment on the left side where it was "left behind" if there is a match.

That's a good idea, and it shouldn't be too hard to do (although there will still be cases where comments are not shown in context)

**Comment by mtlynch** [comment] 2022-09-21 16:58
>So basically for a comment that is "outdated" where there is no right-side line to attach it to, I should show the comment on the left side where it was "left behind" if there is a match.

I'd actually like comments from previous review rounds to always be on the left side of a diff.

My view is that the most logical place for the comment to live is attached to the line + version of code where the reviewer made the comment, which is the left. It gets complicated if a thread lives >1 round, but for the first round at least, left is ideal. This is what Gerrit and Reviewable do.

**Comment by mtlynch** [comment] 2022-11-16 20:57
I'd like to ping this again because it's a continuing pain point to not have this available.

Especially when reviewing something like Markdown prose or in PRs where there are a lot of comments per round, it's hard to keep track of the discussion because the reviewer has to jump back and forth between the comment thread at the bottom and then try to recall what line of code the thread discussion thread referred to.

**Comment by samatcolumn** [comment] 2022-11-17 18:03
Thanks for the bump! I definitely hear you on this one.

**Comment by samatcodeapprove** [comment] 2022-11-17 18:04
Thanks for the bump! I definitely hear you on this one.

**Comment by samatcodeapprove** [comment] 2022-12-27 12:58
@mtlynch I just deployed a large change to how/where threads are displayed that I believe will address your pain point here. If you notice (for better or for worse) please let me know!

**Comment by mtlynch** [comment] 2022-12-27 13:01
@samatcodeapprove - Okay, awesome! I'm excited to try this out.

**Comment by mtlynch** [comment] 2022-12-27 14:21
@samatcodeapprove - This is definitely an improvement, but I think it's a bit buggy. I just opened a PR where I was the reviewer and there were three rounds of review:

![image](https://user-images.githubusercontent.com/7783288/209679674-69a3b830-974b-49eb-a19f-a4c20cae1534.png)

The author has made changes since my Round 3 notes, so my expectation is that if I choose "Since my last review," I'd see my Round 3 notes on the left and nothing on the right. Instead, I see my Round 3 notes on the left and my Round 1 notes on the right:

![image](https://user-images.githubusercontent.com/7783288/209679483-a0efbdfc-80de-4d36-b4a4-18e8afb1c75c.png)

Is it possible to hide the Round 1 notes? I'd only expect to see them if I was diffing Round 1 vs a later commit.

**Comment by samatcodeapprove** [comment] 2022-12-27 14:48
@mtlynch thanks for the specific test case! This is currently intended behavior but I can see how it's not desirable. Right now I show a comment inline if I can attach it by its original context or its updated context. 

So in "since review X" mode it seems that you're expecting a hard time window filter on both code and comments, which makes sense. But what would you expect if those Round 1 comments were still unresolved? Would you still want them hidden in "since review X" view?

**Comment by mtlynch** [comment] 2022-12-27 15:24
>So in "since review X" mode it seems that you're expecting a hard time window filter on both code and comments, which makes sense. But what would you expect if those Round 1 comments were still unresolved? Would you still want them hidden in "since review X" view?

If Round 1 comments were still unresolved in Round 2 or 3, I'd expect to see them on the left-hand side of the diff in "Since Round 2" or "Since Round 3" views.

I tried to reverse engineer my expectations, and here's how I'd describe them:

* When a comment thread falls on the exact border of a diff, show the thread in the exact context where they were created
  * By exact border, I mean that if there are two rounds of a review, then a round 1 comment would be on the exact border of a base vs. round 1 view or a round 1 vs. round 2 view, but it would not be on an exact border in a base vs round 2 view
  * e.g., if a comment was made in round 1, then diffing base vs. round 1 should show the thread on the right, diffing round 1 vs round 2 should show the thread on the left
* If a comment thread is resolved, it should be hidden unless it falls on the exact border of a diff
  * e.g., a resolved round 1 thread should be hidden in round 1 vs round 2 diff and a base vs round 2 diff, but it should show in base vs round 1 and round 1 vs. round 2
* If a comment thread is unresolved, it should show in any diff view >= the round it started, as long as it can attach to a line in the view
  * e.g., an unresolved round 1 thread should still show in round 2 vs. round 3 if the line still exists
  * e.g., an unresolved round 2 thread should show in all rounds >= 2, but it shouldn't show in base vs. round 1

| Thread type | Base vs. Round 1 | Base vs. Round 2 | Round 1 vs. Round 2 | Base vs. Round 3 | Round 1 vs. Round 3 | Round 2 vs. Round 3 |
|-------------|----------|-------------------|-----------------------|-------------------|----------------------|------|
| Unresolved Round 1 thread | Visible on right | Visible on left | Visible on left | Visible on left | Visible on left | Hidden |
| Resolved Round 1 thread | Visible on right |  Hidden  | Visible on left | Hidden | Hidden | Hidden |
| Unresolved Round 2 thread | Hidden | Visible on right | Visible on right | Visible on left | Visible on left | Visible on left |
| Resolved Round 2 thread | Hidden |  Visible on right | Visible on right | Hidden | Hidden | Visible on left |

**Comment by samatcodeapprove** [comment] 2022-12-27 15:36
@mtlynch wow thank you for the super detailed thoughts! I will take some time to digest this.

**Comment by samatcodeapprove** [comment] 2022-12-28 15:48
@mtlynch ok I am deploying some more changes now that get the state a lot closer to the world in your table (although not exactly, since I am trying to keep the mental model a little bit simpler than that).

If you notice the difference let me know what you think!

**Comment by mtlynch** [comment] 2022-12-28 16:12
@samatcodeapprove - Cool, I checked out the PR I referenced [upthread](https://github.com/codeapprove/feedback/issues/63#issuecomment-1365938317), and the new version is closer to my mental model. Thanks! I'll let you know how it goes as we continue doing reviews.

**Comment by mtlynch** [comment] 2023-01-06 16:36
Just wanted to follow up to say that the new behavior is a big improvement! It's really helpful as the author to be able to see notes from my reviewer on the left, my changes on the right to verify I've addressed all my reviewer's notes.

We haven't had a lot of longer reviews since this changed, but I'll follow up to let you know how it works as we do more multi-round reviews.

**Comment by samatcodeapprove** [comment] 2023-01-06 16:40
@mtlynch thanks for following up! I am really happy to hear that it's an improvement and that there are not (yet) major downsides.

I'm going to close this issue for now and if/when you come up with more ways to improve this let's tackle it in smaller more specific threads.

**Closed as completed by samatcodeapprove** 2023-01-06 16:40 UTC
Labels: enhancement
