### ISSUE TITLE
Backticks prevent keyboard from moving the cursor

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#49] opened 2022-08-29 15:00 UTC
I've run into a strange issue in CodeApprove where I get into a state where keyboard arrow keys stop moving the cursor.

![image](https://user-images.githubusercontent.com/7783288/187231826-0803951e-e286-4a08-ad64-85b4fb844e6e.png)

If I type the following markdown in a code comment, it freezes the cursor to keyboard arrow keys, and I can only move the cursor with the mouse:

````
```
##
````

In other words:

1. Type three backticks
2. Hit Enter key
3. Type Shift+3 twice to make two hash mark keys (on en-us keyboard)

After this, the cursor does not respond to up/down arrow keys anymore. I can only move the cursor by typing more or moving it elsewhere with the mouse.

**Comment by samatcodeapprove** [comment] 2022-08-29 19:50
Huh that's a very specific bug, thank you for flagging this! I was able to reproduce it ... it seems to actually only affect the up/down arrow keys not left/right which is even stranger.

**Comment by samatcodeapprove** [comment] 2022-08-31 18:09
Note to self: this is caused by the `##` and the interaction that has with the feature where `#` pops open an issue selector. That selector is eating the up/down arrow key events.

**Comment by samatcodeapprove** [comment] 2022-09-01 07:28
Pushing a fix for this now!

**Closed as completed by samatcodeapprove** 2022-09-01 07:28 UTC
Labels: bug
